[project]
name = "berlin-electoral-districts-geodata"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dacite==1.8.1",
    "geopandas>=1.0.1",
    "pandas==2.2.3",
    "pyyaml==6.0.2",
    "requests==2.32.3",
]
